//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidario.GeneradorEncuestas.UIWeb.WSFormularios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoFormulario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DtoFormulario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoPregunta> PreguntasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoPregunta> Preguntas {
            get {
                return this.PreguntasField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntasField, value) != true)) {
                    this.PreguntasField = value;
                    this.RaisePropertyChanged("Preguntas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoPregunta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DtoPregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private int OrdenField;
        
        private bool EsObligatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoTipoPregunta TipoPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoValoresPregunta> ValoresPreguntaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool EsObligatorio {
            get {
                return this.EsObligatorioField;
            }
            set {
                if ((this.EsObligatorioField.Equals(value) != true)) {
                    this.EsObligatorioField = value;
                    this.RaisePropertyChanged("EsObligatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoTipoPregunta TipoPregunta {
            get {
                return this.TipoPreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPreguntaField, value) != true)) {
                    this.TipoPreguntaField = value;
                    this.RaisePropertyChanged("TipoPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Collections.Generic.List<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoValoresPregunta> ValoresPregunta {
            get {
                return this.ValoresPreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresPreguntaField, value) != true)) {
                    this.ValoresPreguntaField = value;
                    this.RaisePropertyChanged("ValoresPregunta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTipoPregunta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DtoTipoPregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoValoresPregunta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DtoValoresPregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        private int OrdenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSFormularios.FormulariosSoap")]
    public interface FormulariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigoFormulario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormularioPorCodigo", ReplyAction="*")]
        Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponse GetFormularioPorCodigo(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormularioPorCodigo", ReplyAction="*")]
        System.Threading.Tasks.Task<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponse> GetFormularioPorCodigoAsync(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormularioPorCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormularioPorCodigo", Namespace="http://tempuri.org/", Order=0)]
        public Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequestBody Body;
        
        public GetFormularioPorCodigoRequest() {
        }
        
        public GetFormularioPorCodigoRequest(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFormularioPorCodigoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoFormulario;
        
        public GetFormularioPorCodigoRequestBody() {
        }
        
        public GetFormularioPorCodigoRequestBody(string codigoFormulario) {
            this.codigoFormulario = codigoFormulario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormularioPorCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormularioPorCodigoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponseBody Body;
        
        public GetFormularioPorCodigoResponse() {
        }
        
        public GetFormularioPorCodigoResponse(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFormularioPorCodigoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoFormulario GetFormularioPorCodigoResult;
        
        public GetFormularioPorCodigoResponseBody() {
        }
        
        public GetFormularioPorCodigoResponseBody(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoFormulario GetFormularioPorCodigoResult) {
            this.GetFormularioPorCodigoResult = GetFormularioPorCodigoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FormulariosSoapChannel : Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormulariosSoapClient : System.ServiceModel.ClientBase<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap>, Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap {
        
        public FormulariosSoapClient() {
        }
        
        public FormulariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormulariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormulariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormulariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponse Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap.GetFormularioPorCodigo(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest request) {
            return base.Channel.GetFormularioPorCodigo(request);
        }
        
        public Solidario.GeneradorEncuestas.UIWeb.WSFormularios.DtoFormulario GetFormularioPorCodigo(string codigoFormulario) {
            Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest inValue = new Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest();
            inValue.Body = new Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequestBody();
            inValue.Body.codigoFormulario = codigoFormulario;
            Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponse retVal = ((Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap)(this)).GetFormularioPorCodigo(inValue);
            return retVal.Body.GetFormularioPorCodigoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponse> Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap.GetFormularioPorCodigoAsync(Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest request) {
            return base.Channel.GetFormularioPorCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoResponse> GetFormularioPorCodigoAsync(string codigoFormulario) {
            Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest inValue = new Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequest();
            inValue.Body = new Solidario.GeneradorEncuestas.UIWeb.WSFormularios.GetFormularioPorCodigoRequestBody();
            inValue.Body.codigoFormulario = codigoFormulario;
            return ((Solidario.GeneradorEncuestas.UIWeb.WSFormularios.FormulariosSoap)(this)).GetFormularioPorCodigoAsync(inValue);
        }
    }
}
