//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidario.GeneradorEncuestas.Servicio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresPregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValoresPregunta()
        {
            this.Respuestas = new HashSet<Respuesta>();
        }
    
        public int IdValoresPregunta { get; set; }
        public int IdPregunta { get; set; }
        public string Valor { get; set; }
        public int Orden { get; set; }
        public bool EsVisible { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuestas { get; set; }
    }
}
